// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwZE_0b0ldEQ_aW4buhaOrdO9DwmaDW0',
    appId: '1:372461374269:android:448441677305dee2f1d354',
    messagingSenderId: '372461374269',
    projectId: 'onstar-application',
    storageBucket: 'onstar-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNFWRq_9j5Ev4QlfmU4hvnPO8SWwAXG8Q',
    appId: '1:372461374269:ios:6732cf649f5b91ddf1d354',
    messagingSenderId: '372461374269',
    projectId: 'onstar-application',
    storageBucket: 'onstar-application.appspot.com',
    androidClientId: '372461374269-jlsethn9r7pms4i5kehg9lk5lm6b6nkf.apps.googleusercontent.com',
    iosClientId: '372461374269-p6o8ghc9i7fsut852mpppt95trrit74u.apps.googleusercontent.com',
    iosBundleId: 'com.example.onstaraapplication',
  );
}
